Repository Web-Dev-Path/web-dev-path, pull requests merged in 2025-09, with the labels that each got.

#291 Fix/contactus form field bug
  CHANGELOG.md
  styles/pages/contact.module.scss
Labels: bug

#280 Refactor scss CardContainer
  CHANGELOG.md
  components/ContactUs/ContactUsCards/index.js
  components/blog/BlogPostsContainer/index.js
  components/containers/Card/AboutUsCard.js
  components/containers/Card/BlogCard.js
  components/containers/Card/CardInterface.js
  components/containers/Card/Cards.module.scss
  components/containers/Card/ContactUsCard.js
  components/containers/Card/index.js
  components/containers/Card/styles.js
  package-lock.json
  pages/about.js
  styles/_mixins.scss
  yarn.lock
Labels: migration-task

#293 Add Oluwatobi to about us
  CHANGELOG.md
  public/images/oluwatobi.webp
  utils/about.js
Labels: documentation
